import { Inter } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import 'react-toastify/dist/ReactToastify.css';
import "@uploadthing/react/styles.css";
import { StyledEngineProvider } from "@mui/material";
import { AuthProvider } from "./Providers";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <StyledEngineProvider>

          <AuthProvider>{children}</AuthProvider>


        </StyledEngineProvider>

      </body>
    </html>
  );
}
